// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYuavLFztniC0ACqSBH7_DyTRAZ_FRhhQ',
    appId: '1:205692023821:web:fdf44c334774fe12aa5144',
    messagingSenderId: '205692023821',
    projectId: 'greengrid-c75f2',
    authDomain: 'greengrid-c75f2.firebaseapp.com',
    storageBucket: 'greengrid-c75f2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAG4HiArHN0OPysKq550SsFhuc9vky9u0s',
    appId: '1:205692023821:android:262175b70b8e23e3aa5144',
    messagingSenderId: '205692023821',
    projectId: 'greengrid-c75f2',
    storageBucket: 'greengrid-c75f2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB87fMedrk_TRf2zoUJjlMPR0UpiO8P7y0',
    appId: '1:205692023821:ios:fbeb33b6678a5f50aa5144',
    messagingSenderId: '205692023821',
    projectId: 'greengrid-c75f2',
    storageBucket: 'greengrid-c75f2.firebasestorage.app',
    iosBundleId: 'com.example.greengrid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB87fMedrk_TRf2zoUJjlMPR0UpiO8P7y0',
    appId: '1:205692023821:ios:fbeb33b6678a5f50aa5144',
    messagingSenderId: '205692023821',
    projectId: 'greengrid-c75f2',
    storageBucket: 'greengrid-c75f2.firebasestorage.app',
    iosBundleId: 'com.example.greengrid',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYuavLFztniC0ACqSBH7_DyTRAZ_FRhhQ',
    appId: '1:205692023821:web:e5414c2370aa0c9caa5144',
    messagingSenderId: '205692023821',
    projectId: 'greengrid-c75f2',
    authDomain: 'greengrid-c75f2.firebaseapp.com',
    storageBucket: 'greengrid-c75f2.firebasestorage.app',
  );
}
